CREATE TABLE car_entity
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    make    VARCHAR(255),
    model   VARCHAR(255),
    year    INTEGER,
    price   DOUBLE PRECISION,
    is_used BOOLEAN,
    CONSTRAINT pk_carentity PRIMARY KEY (id)
);