spring:
  application:
    name: ProjectFive

  datasource:
    url: jdbc:postgresql://localhost:5439/projectfive
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
  flyway:
    enabled: true
    locations: classpath:db.migration
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
server:
  port: 8080

